Update the README now we have our first release
strimzi/kafka-access-operator pull request #63
Opened 2024-11-05 10:12 UTC by katheris

2024-11-05 10:15 UTC, Frawless commented on packaging/helm-charts/helm3/strimzi-access-operator/README.md
> +To install the chart with the release name `my-strimzi-drain-cleaner`:
```suggestion
To install the chart with the release name `my-strimzi-access-operator`:
```

2024-11-05 10:23 UTC, katheris commented on packaging/helm-charts/helm3/strimzi-access-operator/README.md
> +To install the chart with the release name `my-strimzi-drain-cleaner`:
Good spot!

2024-11-05 10:59 UTC, ppatierno approved these changes

2024-11-05 11:08 UTC, see-quick approved these changes
LGTM

2024-11-05 17:19 UTC, Frawless approved these changes

2024-11-06 04:03 UTC, scholzj requested changes

2024-11-06 04:03 UTC, scholzj commented on README.md
> +### Starting the Access Operator
It is really deploying or installing and not starting it.

2024-11-08 03:39 UTC, scholzj approved these changes

2024-11-08 03:47 UTC, merged